# Generated by Django 5.1.7 on 2025-05-08 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='title',
            field=models.CharField(default='qBQSnP4m0JusaT7v0g9TVWsTLX440ZMvfbySQAfSgG055ClamA', max_length=255),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('duration_description', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.host')),
            ],
        ),
    ]
