# Generated by Django 5.1.7 on 2025-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_challengesubmission_title_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/competitions/cover_images'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='title',
            field=models.CharField(default='Ea2aoRxHz9uClvgHzE3zdomwdUchVcUUVfijsMLc02jpsRiI1y', max_length=255),
        ),
    ]
