# Generated by Django 5.1.7 on 2025-05-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_program_cover_image_alter_challengesubmission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ManyToManyField(to='resources.category'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.host'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
